---
- name: edit grub cfg
  gather_facts: no
  hosts: '{{host}}'
  become: true
  vars:
      varib:
      - biosdevname 
      - net.ifnames 

  tasks:

  - name: edit grub2
    lineinfile:
     path: /etc/default/grub
     regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ item | regex_escape }}=).)*)(?:[" ]{{ item | regex_escape }}=\S+)?(.*")$'
     line: '\1 {{ item }}=0\2'
     backrefs: yes
    loop: "{{varib}}"
    notify: mkconfig

  handlers:

  - name: mkconfig
    command: 
     cmd: 'grub2-mkconfig'
