---
- name: install httpd, add firewall rules, add index.html
  hosts: '{{host}}'
  strategy: free
  vars:
        pack:
              - firewalld
              - httpd
  tasks:

     - name: Install fw apache
       yum: 
        name: "{{ item }}"
        update_cache: yes
        state: present
       loop: "{{pack}}"

     - name: run services
       service: 
        name: "{{item}}"
        state: started
        enabled: yes
       loop: "{{pack}}"

     - name: add http in firewall
       firewalld:
        state: enabled
        permanent: yes
        immediate: yes
        service: http

     - name: create index.html
       copy: 
        dest: /var/www/html/index.html
        content: '"Welcome to my web server"' 
