---
- name: add users
  hosts: '{{host}}'
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:

  - name: Add the users, create home, add comment
    user:
     name: "{{item.key}}"
     create_home: true
     comment: "{{item.key}}@example.com"
     password: "{{item.value}}"
     update_password: on_create
    loop: "{{ lookup('dict',user) }}"
